### ISSUE TITLE
Open search dropdown again after pressing ctrl+k

### ISSUE THREAD

**Issue by Goregius** [easyops-cn/docusaurus-search-local#146]
Currently after searching for something and then pressing ctrl+k or clicking on the search bar, the search menu doesn't show. It would be nice to be able to show in this case. This is useful when trying to search for titles that have duplicated names.

**Comment by weareoutman** [comment]
Yes, this is the desired behavior, however I can't make it work currently. Help wanted and PRs welcome.

**Comment by Goregius** [comment]
I tried running the project locally, and while it works with the released version on npm, the local version runs into the ```shell Error: Cannot mix different versions of joi schemas``` error (#144).  I used yarn link and yarn start to test it locally.

**Comment by SebastianSchuetze** [comment]
docusauraus start command does not support search index.

Maybe you want to use docusaurus serve instead.

**Comment by Goregius** [comment]
Sorry I meant ```yarn start``` from the docusaurus-search-local folder. I was using ```yarn build``` in the docusaurus folder.

**Comment by weareoutman** [comment]
@Goregius currently there is a problem of `joi` conflict when you using `yarn link`. Here is a workaround: go to your docusaurus project and run `yarn why joi` you will get a version of joi. Then go to your docusaurus-search-local folder and run `yarn why joi`, you will get another version of joi. The versions maybe different, you can add code like below in your docusaurus-search-local folder, to make them use the same version. of joi:

```
  "resolutions": {
    "joi": "VERSION"
  }
```

Change `VERSION` to the exactly same version of your docusaurus project.

Remember not to commit this change to your PR, since it's only a temporary workaround to fix issues with `yarn link`.

**Comment by weareoutman** [comment]
Closed via #147 and released in v0.22.0
