### ISSUE TITLE
Hash in search index json filename

### ISSUE THREAD

**Issue by fawazahmed0** [easyops-cn/docusaurus-search-local#171]
Hi, I think it would be better to save hash in filename, something like [this](https://github.com/fawazahmed0/docusaurus-search-local/commit/158fc59bbe90825378fdc61062d7d626756c3d13) 
If we use the above, then we can fetch from open source cdn's like [raw.githack](https://raw.githack.com/) etc.
Github pages usually have [bandwidth limits](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)

This is useful when the json file size is huge in size

**Comment by weareoutman** [comment]
Yes, it's reasonable, I think we can provide an option so that users can opt-in this feature.

We may keep the current behavior by default, since using hash filenames may cause other problems, E.g., if the user loads one of your pages, you deploy an update, then the user clicks the search bar to fetch the index json, then the old page may try to load a file which is gone. See [this article](https://jakearchibald.com/2020/multiple-versions-same-time/).

**Comment by weareoutman** [comment]
Released in v0.30.0

<img width="851" alt="image" src="https://user-images.githubusercontent.com/2338946/180353575-7d0d5719-9c49-45f6-97e0-2d311fc19e73.png">
